//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetHero.App.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BudgetHero.App.Resources.Languages.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budżety.
        /// </summary>
        internal static string BudgetsView_Title {
            get {
                return ResourceManager.GetString("BudgetsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kokpit.
        /// </summary>
        internal static string DashboardView_Title {
            get {
                return ResourceManager.GetString("DashboardView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lub wybierz jeden z proponowanych poniżej.
        /// </summary>
        internal static string FirstSetup_BudgetContentView_BoxViewSeparator_Package {
            get {
                return ResourceManager.GetString("FirstSetup_BudgetContentView_BoxViewSeparator_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string FirstSetup_BudgetContentView_Entry_Description {
            get {
                return ResourceManager.GetString("FirstSetup_BudgetContentView_Entry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        internal static string FirstSetup_BudgetContentView_Entry_Name {
            get {
                return ResourceManager.GetString("FirstSetup_BudgetContentView_Entry_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliknij by wybrać przypisaną ikonę.
        /// </summary>
        internal static string FirstSetup_BudgetContentView_Label_Icon_Hint {
            get {
                return ResourceManager.GetString("FirstSetup_BudgetContentView_Label_Icon_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie budżetu.
        /// </summary>
        internal static string FirstSetup_BudgetContentView_SubTitle {
            get {
                return ResourceManager.GetString("FirstSetup_BudgetContentView_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akualnie dodane kategorie w budżecie.
        /// </summary>
        internal static string FirstSetup_CategoriesContentView_BoxViewSeparator_Categories {
            get {
                return ResourceManager.GetString("FirstSetup_CategoriesContentView_BoxViewSeparator_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string FirstSetup_CategoriesContentView_Button_Add {
            get {
                return ResourceManager.GetString("FirstSetup_CategoriesContentView_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        internal static string FirstSetup_CategoriesContentView_Entry_Name {
            get {
                return ResourceManager.GetString("FirstSetup_CategoriesContentView_Entry_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliknij by wybrać przypisaną ikonę.
        /// </summary>
        internal static string FirstSetup_CategoriesContentView_Label_Hint {
            get {
                return ResourceManager.GetString("FirstSetup_CategoriesContentView_Label_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie kategorii.
        /// </summary>
        internal static string FirstSetup_CategoriesContentView_SubTitle {
            get {
                return ResourceManager.GetString("FirstSetup_CategoriesContentView_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj w BudgetHero.
        /// </summary>
        internal static string FirstSetup_Label_Welcome_Title_1 {
            get {
                return ResourceManager.GetString("FirstSetup_Label_Welcome_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przed tobą ostatni krok..
        /// </summary>
        internal static string FirstSetup_Label_Welcome_Title_2 {
            get {
                return ResourceManager.GetString("FirstSetup_Label_Welcome_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz swój pierwszy budżet!.
        /// </summary>
        internal static string FirstSetup_Label_Welcome_Title_3 {
            get {
                return ResourceManager.GetString("FirstSetup_Label_Welcome_Title_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        internal static string FirstSetup_UserContentView_Entry_FirstName {
            get {
                return ResourceManager.GetString("FirstSetup_UserContentView_Entry_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        internal static string FirstSetup_UserContentView_Entry_LastName {
            get {
                return ResourceManager.GetString("FirstSetup_UserContentView_Entry_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu.
        /// </summary>
        internal static string FirstSetup_UserContentView_Entry_PhoneNumber {
            get {
                return ResourceManager.GetString("FirstSetup_UserContentView_Entry_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane użytkownika.
        /// </summary>
        internal static string FirstSetup_UserContentView_SubTitle {
            get {
                return ResourceManager.GetString("FirstSetup_UserContentView_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budżet.
        /// </summary>
        internal static string FirstSetupCarouselItemViewsType_BudgetSetup {
            get {
                return ResourceManager.GetString("FirstSetupCarouselItemViewsType_BudgetSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        internal static string FirstSetupCarouselItemViewsType_Categories {
            get {
                return ResourceManager.GetString("FirstSetupCarouselItemViewsType_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik.
        /// </summary>
        internal static string FirstSetupCarouselItemViewsType_UserSetup {
            get {
                return ResourceManager.GetString("FirstSetupCarouselItemViewsType_UserSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót.
        /// </summary>
        internal static string FirstSetupView_Button_Back {
            get {
                return ResourceManager.GetString("FirstSetupView_Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalej.
        /// </summary>
        internal static string FirstSetupView_Button_Next {
            get {
                return ResourceManager.GetString("FirstSetupView_Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguracja startowa.
        /// </summary>
        internal static string FirstSetupView_Title {
            get {
                return ResourceManager.GetString("FirstSetupView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępne wkrótce.
        /// </summary>
        internal static string General_Views_IsNotEnable {
            get {
                return ResourceManager.GetString("General_Views_IsNotEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybór ikony.
        /// </summary>
        internal static string IconSelectContentView_Title {
            get {
                return ResourceManager.GetString("IconSelectContentView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lub.
        /// </summary>
        internal static string LoginContentView_BoxViewSeparator_Or {
            get {
                return ResourceManager.GetString("LoginContentView_BoxViewSeparator_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomniałem hasła.
        /// </summary>
        internal static string LoginContentView_Button_ForgotPassword {
            get {
                return ResourceManager.GetString("LoginContentView_Button_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        internal static string LoginContentView_Button_Login {
            get {
                return ResourceManager.GetString("LoginContentView_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj mnie.
        /// </summary>
        internal static string LoginContentView_Checkbox_RememberMe {
            get {
                return ResourceManager.GetString("LoginContentView_Checkbox_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginContentView_Entry_Email {
            get {
                return ResourceManager.GetString("LoginContentView_Entry_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        internal static string LoginContentView_Entry_Password {
            get {
                return ResourceManager.GetString("LoginContentView_Entry_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        internal static string MainCarouselItemViewType_Login {
            get {
                return ResourceManager.GetString("MainCarouselItemViewType_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        internal static string MainCarouselItemViewType_Register {
            get {
                return ResourceManager.GetString("MainCarouselItemViewType_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj w BudgetHero.
        /// </summary>
        internal static string MainView_Label_Welcome_Title_1 {
            get {
                return ResourceManager.GetString("MainView_Label_Welcome_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bądź bohaterem swoich finansów..
        /// </summary>
        internal static string MainView_Label_Welcome_Title_2 {
            get {
                return ResourceManager.GetString("MainView_Label_Welcome_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się do swojego konta lub dołącz poprzez rejestrację..
        /// </summary>
        internal static string MainView_Label_Welcome_Title_3 {
            get {
                return ResourceManager.GetString("MainView_Label_Welcome_Title_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestruj.
        /// </summary>
        internal static string RegisterContentView_Button_Register {
            get {
                return ResourceManager.GetString("RegisterContentView_Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string RegisterContentView_Entry_Email {
            get {
                return ResourceManager.GetString("RegisterContentView_Entry_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        internal static string RegisterContentView_Entry_Password {
            get {
                return ResourceManager.GetString("RegisterContentView_Entry_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź hasło.
        /// </summary>
        internal static string RegisterContentView_Entry_PasswordRepeated {
            get {
                return ResourceManager.GetString("RegisterContentView_Entry_PasswordRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalna długość to 8 znaków.
        /// </summary>
        internal static string RegisterContentView_Label_Password_Hint_1 {
            get {
                return ResourceManager.GetString("RegisterContentView_Label_Password_Hint_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zawiera cyfry, litery (duże i małe).
        /// </summary>
        internal static string RegisterContentView_Label_Password_Hint_2 {
            get {
                return ResourceManager.GetString("RegisterContentView_Label_Password_Hint_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zawiera znaki specjalne (no. ?!@#$%).
        /// </summary>
        internal static string RegisterContentView_Label_Password_Hint_3 {
            get {
                return ResourceManager.GetString("RegisterContentView_Label_Password_Hint_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporty.
        /// </summary>
        internal static string ReportsView_Title {
            get {
                return ResourceManager.GetString("ReportsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słupkowy.
        /// </summary>
        internal static string ReportType_GraphBar {
            get {
                return ResourceManager.GetString("ReportType_GraphBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kołowy.
        /// </summary>
        internal static string ReportType_GraphPie {
            get {
                return ResourceManager.GetString("ReportType_GraphPie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelaryczny.
        /// </summary>
        internal static string ReportType_Table {
            get {
                return ResourceManager.GetString("ReportType_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        internal static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transakcje.
        /// </summary>
        internal static string TransactionsView_Title {
            get {
                return ResourceManager.GetString("TransactionsView_Title", resourceCulture);
            }
        }
    }
}
