//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetHero.App.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BudgetHero.App.Resources.Languages.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budżet.
        /// </summary>
        internal static string FirstSetupCarouselItemViewsType_BudgetSetup {
            get {
                return ResourceManager.GetString("FirstSetupCarouselItemViewsType_BudgetSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        internal static string FirstSetupCarouselItemViewsType_Categories {
            get {
                return ResourceManager.GetString("FirstSetupCarouselItemViewsType_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik.
        /// </summary>
        internal static string FirstSetupCarouselItemViewsType_UserSetup {
            get {
                return ResourceManager.GetString("FirstSetupCarouselItemViewsType_UserSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        internal static string MainCarouselItemViewType_Login {
            get {
                return ResourceManager.GetString("MainCarouselItemViewType_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        internal static string MainCarouselItemViewType_Register {
            get {
                return ResourceManager.GetString("MainCarouselItemViewType_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słupkowy.
        /// </summary>
        internal static string ReportType_GraphBar {
            get {
                return ResourceManager.GetString("ReportType_GraphBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kołowy.
        /// </summary>
        internal static string ReportType_GraphPie {
            get {
                return ResourceManager.GetString("ReportType_GraphPie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelaryczny.
        /// </summary>
        internal static string ReportType_Table {
            get {
                return ResourceManager.GetString("ReportType_Table", resourceCulture);
            }
        }
    }
}
