//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetHero.App.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BudgetHero.App.Resources.Languages.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string AddBudgetContentView_Button_Add {
            get {
                return ResourceManager.GetString("AddBudgetContentView_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string AddBudgetContentView_Entry_Description {
            get {
                return ResourceManager.GetString("AddBudgetContentView_Entry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        internal static string AddBudgetContentView_Entry_Name {
            get {
                return ResourceManager.GetString("AddBudgetContentView_Entry_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliknij by wybrać przypisaną ikonę.
        /// </summary>
        internal static string AddBudgetContentView_Label_Icon_Hint {
            get {
                return ResourceManager.GetString("AddBudgetContentView_Label_Icon_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj budżet.
        /// </summary>
        internal static string AddBudgetContentView_Title {
            get {
                return ResourceManager.GetString("AddBudgetContentView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły budżetu.
        /// </summary>
        internal static string BudgetDetailView_Title {
            get {
                return ResourceManager.GetString("BudgetDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Własne.
        /// </summary>
        internal static string BudgetListType_Own {
            get {
                return ResourceManager.GetString("BudgetListType_Own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Współdzielone.
        /// </summary>
        internal static string BudgetListType_Shared {
            get {
                return ResourceManager.GetString("BudgetListType_Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budżety.
        /// </summary>
        internal static string BudgetsView_Title {
            get {
                return ResourceManager.GetString("BudgetsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kokpit.
        /// </summary>
        internal static string DashboardView_Title {
            get {
                return ResourceManager.GetString("DashboardView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włąsny.
        /// </summary>
        internal static string DateFilterType_Own {
            get {
                return ResourceManager.GetString("DateFilterType_Own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 miesięcy.
        /// </summary>
        internal static string DateFilterType_SixMonths {
            get {
                return ResourceManager.GetString("DateFilterType_SixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten miesiąc.
        /// </summary>
        internal static string DateFilterType_ThisMonth {
            get {
                return ResourceManager.GetString("DateFilterType_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten rok.
        /// </summary>
        internal static string DateFilterType_ThisYear {
            get {
                return ResourceManager.GetString("DateFilterType_ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 miesiące.
        /// </summary>
        internal static string DateFilterType_ThreeMonths {
            get {
                return ResourceManager.GetString("DateFilterType_ThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 miesięcy.
        /// </summary>
        internal static string DateFilterType_TwelveMonths {
            get {
                return ResourceManager.GetString("DateFilterType_TwelveMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtruj.
        /// </summary>
        internal static string FilterTransactionsContentView_Button_Filter {
            get {
                return ResourceManager.GetString("FilterTransactionsContentView_Button_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetuj.
        /// </summary>
        internal static string FilterTransactionsContentView_Button_Reset {
            get {
                return ResourceManager.GetString("FilterTransactionsContentView_Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data od.
        /// </summary>
        internal static string FilterTransactionsContentView_DatePicker_DateFrom {
            get {
                return ResourceManager.GetString("FilterTransactionsContentView_DatePicker_DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data do.
        /// </summary>
        internal static string FilterTransactionsContentView_DatePicker_DateTo {
            get {
                return ResourceManager.GetString("FilterTransactionsContentView_DatePicker_DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota od.
        /// </summary>
        internal static string FilterTransactionsContentView_Entry_PriceFrom {
            get {
                return ResourceManager.GetString("FilterTransactionsContentView_Entry_PriceFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota do.
        /// </summary>
        internal static string FilterTransactionsContentView_Entry_PriceTo {
            get {
                return ResourceManager.GetString("FilterTransactionsContentView_Entry_PriceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz kategorie.
        /// </summary>
        internal static string FilterTransactionsContentView_Label_SelectCategoty_Hint {
            get {
                return ResourceManager.GetString("FilterTransactionsContentView_Label_SelectCategoty_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybrane kategorie.
        /// </summary>
        internal static string FilterTransactionsContentView_Label_SelectedCategories_Hint {
            get {
                return ResourceManager.GetString("FilterTransactionsContentView_Label_SelectedCategories_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtruj transakcje.
        /// </summary>
        internal static string FilterTransactionsContentView_Title {
            get {
                return ResourceManager.GetString("FilterTransactionsContentView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lub wybierz jeden z proponowanych poniżej.
        /// </summary>
        internal static string FirstSetup_BudgetContentView_BoxViewSeparator_Package {
            get {
                return ResourceManager.GetString("FirstSetup_BudgetContentView_BoxViewSeparator_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string FirstSetup_BudgetContentView_Entry_Description {
            get {
                return ResourceManager.GetString("FirstSetup_BudgetContentView_Entry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        internal static string FirstSetup_BudgetContentView_Entry_Name {
            get {
                return ResourceManager.GetString("FirstSetup_BudgetContentView_Entry_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliknij by wybrać przypisaną ikonę.
        /// </summary>
        internal static string FirstSetup_BudgetContentView_Label_Icon_Hint {
            get {
                return ResourceManager.GetString("FirstSetup_BudgetContentView_Label_Icon_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie budżetu.
        /// </summary>
        internal static string FirstSetup_BudgetContentView_SubTitle {
            get {
                return ResourceManager.GetString("FirstSetup_BudgetContentView_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akualnie dodane kategorie w budżecie.
        /// </summary>
        internal static string FirstSetup_CategoriesContentView_BoxViewSeparator_Categories {
            get {
                return ResourceManager.GetString("FirstSetup_CategoriesContentView_BoxViewSeparator_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string FirstSetup_CategoriesContentView_Button_Add {
            get {
                return ResourceManager.GetString("FirstSetup_CategoriesContentView_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        internal static string FirstSetup_CategoriesContentView_Entry_Name {
            get {
                return ResourceManager.GetString("FirstSetup_CategoriesContentView_Entry_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliknij by wybrać przypisaną ikonę.
        /// </summary>
        internal static string FirstSetup_CategoriesContentView_Label_Hint {
            get {
                return ResourceManager.GetString("FirstSetup_CategoriesContentView_Label_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie kategorii.
        /// </summary>
        internal static string FirstSetup_CategoriesContentView_SubTitle {
            get {
                return ResourceManager.GetString("FirstSetup_CategoriesContentView_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj w BudgetHero.
        /// </summary>
        internal static string FirstSetup_Label_Welcome_Title_1 {
            get {
                return ResourceManager.GetString("FirstSetup_Label_Welcome_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przed tobą ostatni krok..
        /// </summary>
        internal static string FirstSetup_Label_Welcome_Title_2 {
            get {
                return ResourceManager.GetString("FirstSetup_Label_Welcome_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz swój pierwszy budżet!.
        /// </summary>
        internal static string FirstSetup_Label_Welcome_Title_3 {
            get {
                return ResourceManager.GetString("FirstSetup_Label_Welcome_Title_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        internal static string FirstSetup_UserContentView_Entry_FirstName {
            get {
                return ResourceManager.GetString("FirstSetup_UserContentView_Entry_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        internal static string FirstSetup_UserContentView_Entry_LastName {
            get {
                return ResourceManager.GetString("FirstSetup_UserContentView_Entry_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu.
        /// </summary>
        internal static string FirstSetup_UserContentView_Entry_PhoneNumber {
            get {
                return ResourceManager.GetString("FirstSetup_UserContentView_Entry_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane użytkownika.
        /// </summary>
        internal static string FirstSetup_UserContentView_SubTitle {
            get {
                return ResourceManager.GetString("FirstSetup_UserContentView_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budżet.
        /// </summary>
        internal static string FirstSetupCarouselItemViewsType_BudgetSetup {
            get {
                return ResourceManager.GetString("FirstSetupCarouselItemViewsType_BudgetSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        internal static string FirstSetupCarouselItemViewsType_Categories {
            get {
                return ResourceManager.GetString("FirstSetupCarouselItemViewsType_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik.
        /// </summary>
        internal static string FirstSetupCarouselItemViewsType_UserSetup {
            get {
                return ResourceManager.GetString("FirstSetupCarouselItemViewsType_UserSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót.
        /// </summary>
        internal static string FirstSetupView_Button_Back {
            get {
                return ResourceManager.GetString("FirstSetupView_Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalej.
        /// </summary>
        internal static string FirstSetupView_Button_Next {
            get {
                return ResourceManager.GetString("FirstSetupView_Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguracja startowa.
        /// </summary>
        internal static string FirstSetupView_Title {
            get {
                return ResourceManager.GetString("FirstSetupView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        internal static string General_DisplayAlert_Confirmation_Accept {
            get {
                return ResourceManager.GetString("General_DisplayAlert_Confirmation_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dodać.
        /// </summary>
        internal static string General_DisplayAlert_Confirmation_Action_Add {
            get {
                return ResourceManager.GetString("General_DisplayAlert_Confirmation_Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usunąć.
        /// </summary>
        internal static string General_DisplayAlert_Confirmation_Action_Delete {
            get {
                return ResourceManager.GetString("General_DisplayAlert_Confirmation_Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaktualizować.
        /// </summary>
        internal static string General_DisplayAlert_Confirmation_Action_Update {
            get {
                return ResourceManager.GetString("General_DisplayAlert_Confirmation_Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        internal static string General_DisplayAlert_Confirmation_Cancel {
            get {
                return ResourceManager.GetString("General_DisplayAlert_Confirmation_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz {0} {1}?.
        /// </summary>
        internal static string General_DisplayAlert_Confirmation_Message_Template {
            get {
                return ResourceManager.GetString("General_DisplayAlert_Confirmation_Message_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz {0} te {1}?.
        /// </summary>
        internal static string General_DisplayAlert_Confirmation_Message_Template_Plural {
            get {
                return ResourceManager.GetString("General_DisplayAlert_Confirmation_Message_Template_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz {0} {1}?.
        /// </summary>
        internal static string General_DisplayAlert_Confirmation_Message_Template_Singular {
            get {
                return ResourceManager.GetString("General_DisplayAlert_Confirmation_Message_Template_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzenie.
        /// </summary>
        internal static string General_DisplayAlert_Confirmation_Title {
            get {
                return ResourceManager.GetString("General_DisplayAlert_Confirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skasuj.
        /// </summary>
        internal static string General_ToolbarItem_Button_Delete {
            get {
                return ResourceManager.GetString("General_ToolbarItem_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string General_ToolbarItem_Button_Save {
            get {
                return ResourceManager.GetString("General_ToolbarItem_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępne wkrótce.
        /// </summary>
        internal static string General_Views_IsNotEnable {
            get {
                return ResourceManager.GetString("General_Views_IsNotEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak elementów.
        /// </summary>
        internal static string General_Views_NoItems {
            get {
                return ResourceManager.GetString("General_Views_NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        internal static string General_Views_Search {
            get {
                return ResourceManager.GetString("General_Views_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto.
        /// </summary>
        internal static string Icon_AccountCircle {
            get {
                return ResourceManager.GetString("Icon_AccountCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string Icon_Add {
            get {
                return ResourceManager.GetString("Icon_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do tyłu.
        /// </summary>
        internal static string Icon_ArrowBackward {
            get {
                return ResourceManager.GetString("Icon_ArrowBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W dół.
        /// </summary>
        internal static string Icon_ArrowDown {
            get {
                return ResourceManager.GetString("Icon_ArrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do przodu.
        /// </summary>
        internal static string Icon_ArrowForward {
            get {
                return ResourceManager.GetString("Icon_ArrowForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W górę.
        /// </summary>
        internal static string Icon_ArrowUp {
            get {
                return ResourceManager.GetString("Icon_ArrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót.
        /// </summary>
        internal static string Icon_Back {
            get {
                return ResourceManager.GetString("Icon_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cofnij.
        /// </summary>
        internal static string Icon_Backspace {
            get {
                return ResourceManager.GetString("Icon_Backspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budżet.
        /// </summary>
        internal static string Icon_Budget {
            get {
                return ResourceManager.GetString("Icon_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblicz.
        /// </summary>
        internal static string Icon_Calculate {
            get {
                return ResourceManager.GetString("Icon_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalendarz.
        /// </summary>
        internal static string Icon_Calendar {
            get {
                return ResourceManager.GetString("Icon_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koniec.
        /// </summary>
        internal static string Icon_CalendarEnds {
            get {
                return ResourceManager.GetString("Icon_CalendarEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Początek.
        /// </summary>
        internal static string Icon_CalendarStart {
            get {
                return ResourceManager.GetString("Icon_CalendarStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string Icon_Cancel {
            get {
                return ResourceManager.GetString("Icon_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoire.
        /// </summary>
        internal static string Icon_Categories {
            get {
                return ResourceManager.GetString("Icon_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozrywka.
        /// </summary>
        internal static string Icon_Category_Entertainment {
            get {
                return ResourceManager.GetString("Icon_Category_Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydażenia.
        /// </summary>
        internal static string Icon_Category_Events {
            get {
                return ResourceManager.GetString("Icon_Category_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przychody i wydatki.
        /// </summary>
        internal static string Icon_Category_ExpensesAndIncome {
            get {
                return ResourceManager.GetString("Icon_Category_ExpensesAndIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedzenie i restauracje.
        /// </summary>
        internal static string Icon_Category_FoodAndRestaurants {
            get {
                return ResourceManager.GetString("Icon_Category_FoodAndRestaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ćwiczenia.
        /// </summary>
        internal static string Icon_Category_Gym {
            get {
                return ResourceManager.GetString("Icon_Category_Gym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakupy.
        /// </summary>
        internal static string Icon_Category_Shopping {
            get {
                return ResourceManager.GetString("Icon_Category_Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        internal static string Icon_Category_Transport {
            get {
                return ResourceManager.GetString("Icon_Category_Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas.
        /// </summary>
        internal static string Icon_Clock {
            get {
                return ResourceManager.GetString("Icon_Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        internal static string Icon_Close {
            get {
                return ResourceManager.GetString("Icon_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połączenie aktywne.
        /// </summary>
        internal static string Icon_CloudDone {
            get {
                return ResourceManager.GetString("Icon_CloudDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połączenie nieaktywne.
        /// </summary>
        internal static string Icon_CloudOff {
            get {
                return ResourceManager.GetString("Icon_CloudOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasuj.
        /// </summary>
        internal static string Icon_Delete {
            get {
                return ResourceManager.GetString("Icon_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        internal static string Icon_Error {
            get {
                return ResourceManager.GetString("Icon_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtruj.
        /// </summary>
        internal static string Icon_Filter {
            get {
                return ResourceManager.GetString("Icon_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtruj listę.
        /// </summary>
        internal static string Icon_FilterList {
            get {
                return ResourceManager.GetString("Icon_FilterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłącz filtrowanie listy.
        /// </summary>
        internal static string Icon_FilterListOff {
            get {
                return ResourceManager.GetString("Icon_FilterListOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykresy.
        /// </summary>
        internal static string Icon_Graphs {
            get {
                return ResourceManager.GetString("Icon_Graphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj do grupy.
        /// </summary>
        internal static string Icon_GroupAdd {
            get {
                return ResourceManager.GetString("Icon_GroupAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń z grupy.
        /// </summary>
        internal static string Icon_GroupRemove {
            get {
                return ResourceManager.GetString("Icon_GroupRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoc.
        /// </summary>
        internal static string Icon_Help {
            get {
                return ResourceManager.GetString("Icon_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia.
        /// </summary>
        internal static string Icon_History {
            get {
                return ResourceManager.GetString("Icon_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kokpit.
        /// </summary>
        internal static string Icon_Home {
            get {
                return ResourceManager.GetString("Icon_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja.
        /// </summary>
        internal static string Icon_Info {
            get {
                return ResourceManager.GetString("Icon_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Icon_Menu {
            get {
                return ResourceManager.GetString("Icon_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalej.
        /// </summary>
        internal static string Icon_Next {
            get {
                return ResourceManager.GetString("Icon_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik.
        /// </summary>
        internal static string Icon_Person {
            get {
                return ResourceManager.GetString("Icon_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj osobę.
        /// </summary>
        internal static string Icon_PersonAdd {
            get {
                return ResourceManager.GetString("Icon_PersonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        internal static string Icon_Remove {
            get {
                return ResourceManager.GetString("Icon_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reszta.
        /// </summary>
        internal static string Icon_Rest {
            get {
                return ResourceManager.GetString("Icon_Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        internal static string Icon_Search {
            get {
                return ResourceManager.GetString("Icon_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        internal static string Icon_Settings {
            get {
                return ResourceManager.GetString("Icon_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortuj.
        /// </summary>
        internal static string Icon_Sort {
            get {
                return ResourceManager.GetString("Icon_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma.
        /// </summary>
        internal static string Icon_Sum {
            get {
                return ResourceManager.GetString("Icon_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizacja aktywna.
        /// </summary>
        internal static string Icon_Sync {
            get {
                return ResourceManager.GetString("Icon_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizacja nieaktywna.
        /// </summary>
        internal static string Icon_SyncOff {
            get {
                return ResourceManager.GetString("Icon_SyncOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj transakcję.
        /// </summary>
        internal static string Icon_TransactionAdd {
            get {
                return ResourceManager.GetString("Icon_TransactionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transakcje.
        /// </summary>
        internal static string Icon_Transactions {
            get {
                return ResourceManager.GetString("Icon_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziel transakcję.
        /// </summary>
        internal static string Icon_TransactionSplit {
            get {
                return ResourceManager.GetString("Icon_TransactionSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypchnij transakcję.
        /// </summary>
        internal static string Icon_TransitionPush {
            get {
                return ResourceManager.GetString("Icon_TransitionPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualizuj.
        /// </summary>
        internal static string Icon_Update {
            get {
                return ResourceManager.GetString("Icon_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widoczny.
        /// </summary>
        internal static string Icon_Visibility {
            get {
                return ResourceManager.GetString("Icon_Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewidoczny.
        /// </summary>
        internal static string Icon_VisibilityOff {
            get {
                return ResourceManager.GetString("Icon_VisibilityOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostrzeżenie.
        /// </summary>
        internal static string Icon_Warning {
            get {
                return ResourceManager.GetString("Icon_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikona {0} nie została zdefiniowana..
        /// </summary>
        internal static string IconHelper_ResourceException_NoIcon {
            get {
                return ResourceManager.GetString("IconHelper_ResourceException_NoIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikona {0} nie posiada przypisanego klucza zasobów..
        /// </summary>
        internal static string IconHelper_ResourceException_NoKey {
            get {
                return ResourceManager.GetString("IconHelper_ResourceException_NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak zasobu dla klucza {0}..
        /// </summary>
        internal static string IconHelper_ResourceException_NoResource {
            get {
                return ResourceManager.GetString("IconHelper_ResourceException_NoResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybór ikony.
        /// </summary>
        internal static string IconSelectContentView_Title {
            get {
                return ResourceManager.GetString("IconSelectContentView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lub.
        /// </summary>
        internal static string LoginContentView_BoxViewSeparator_Or {
            get {
                return ResourceManager.GetString("LoginContentView_BoxViewSeparator_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomniałem hasła.
        /// </summary>
        internal static string LoginContentView_Button_ForgotPassword {
            get {
                return ResourceManager.GetString("LoginContentView_Button_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        internal static string LoginContentView_Button_Login {
            get {
                return ResourceManager.GetString("LoginContentView_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj mnie.
        /// </summary>
        internal static string LoginContentView_Checkbox_RememberMe {
            get {
                return ResourceManager.GetString("LoginContentView_Checkbox_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginContentView_Entry_Email {
            get {
                return ResourceManager.GetString("LoginContentView_Entry_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        internal static string LoginContentView_Entry_Password {
            get {
                return ResourceManager.GetString("LoginContentView_Entry_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        internal static string MainCarouselItemViewType_Login {
            get {
                return ResourceManager.GetString("MainCarouselItemViewType_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        internal static string MainCarouselItemViewType_Register {
            get {
                return ResourceManager.GetString("MainCarouselItemViewType_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj w BudgetHero.
        /// </summary>
        internal static string MainView_Label_Welcome_Title_1 {
            get {
                return ResourceManager.GetString("MainView_Label_Welcome_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bądź bohaterem swoich finansów..
        /// </summary>
        internal static string MainView_Label_Welcome_Title_2 {
            get {
                return ResourceManager.GetString("MainView_Label_Welcome_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się do swojego konta lub dołącz poprzez rejestrację..
        /// </summary>
        internal static string MainView_Label_Welcome_Title_3 {
            get {
                return ResourceManager.GetString("MainView_Label_Welcome_Title_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestruj.
        /// </summary>
        internal static string RegisterContentView_Button_Register {
            get {
                return ResourceManager.GetString("RegisterContentView_Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string RegisterContentView_Entry_Email {
            get {
                return ResourceManager.GetString("RegisterContentView_Entry_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        internal static string RegisterContentView_Entry_Password {
            get {
                return ResourceManager.GetString("RegisterContentView_Entry_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź hasło.
        /// </summary>
        internal static string RegisterContentView_Entry_PasswordRepeated {
            get {
                return ResourceManager.GetString("RegisterContentView_Entry_PasswordRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalna długość to 8 znaków.
        /// </summary>
        internal static string RegisterContentView_Label_Password_Hint_1 {
            get {
                return ResourceManager.GetString("RegisterContentView_Label_Password_Hint_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zawiera cyfry, litery (duże i małe).
        /// </summary>
        internal static string RegisterContentView_Label_Password_Hint_2 {
            get {
                return ResourceManager.GetString("RegisterContentView_Label_Password_Hint_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zawiera znaki specjalne (no. ?!@#$%).
        /// </summary>
        internal static string RegisterContentView_Label_Password_Hint_3 {
            get {
                return ResourceManager.GetString("RegisterContentView_Label_Password_Hint_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokazuj nazwy kategorii razem z ikonami..
        /// </summary>
        internal static string ReportsView_CheckBox_Label_CategoryNameVisible {
            get {
                return ResourceManager.GetString("ReportsView_CheckBox_Label_CategoryNameVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaz udział procentowy..
        /// </summary>
        internal static string ReportsView_CheckBox_Label_PercentageVisible {
            get {
                return ResourceManager.GetString("ReportsView_CheckBox_Label_PercentageVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sumuj pozostałe wydatki jako Reszta. Wymaga ponowienia filtracji..
        /// </summary>
        internal static string ReportsView_CheckBox_Label_SumOtherAsResult {
            get {
                return ResourceManager.GetString("ReportsView_CheckBox_Label_SumOtherAsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydatki sumarycznie.
        /// </summary>
        internal static string ReportsView_Label_AllTransaction {
            get {
                return ResourceManager.GetString("ReportsView_Label_AllTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydatki średnie miesięczne.
        /// </summary>
        internal static string ReportsView_Label_AvgTransaction {
            get {
                return ResourceManager.GetString("ReportsView_Label_AvgTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporty.
        /// </summary>
        internal static string ReportsView_Title {
            get {
                return ResourceManager.GetString("ReportsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słupkowy.
        /// </summary>
        internal static string ReportType_GraphBar {
            get {
                return ResourceManager.GetString("ReportType_GraphBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kołowy.
        /// </summary>
        internal static string ReportType_GraphPie {
            get {
                return ResourceManager.GetString("ReportType_GraphPie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelaryczny.
        /// </summary>
        internal static string ReportType_Table {
            get {
                return ResourceManager.GetString("ReportType_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to budżety.
        /// </summary>
        internal static string Resource_Plural_Budget {
            get {
                return ResourceManager.GetString("Resource_Plural_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kategorie.
        /// </summary>
        internal static string Resource_Plural_Category {
            get {
                return ResourceManager.GetString("Resource_Plural_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to konfiguracje.
        /// </summary>
        internal static string Resource_Plural_Configuration {
            get {
                return ResourceManager.GetString("Resource_Plural_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transakcje.
        /// </summary>
        internal static string Resource_Plural_Transaction {
            get {
                return ResourceManager.GetString("Resource_Plural_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to budżet.
        /// </summary>
        internal static string Resource_Singular_Budget {
            get {
                return ResourceManager.GetString("Resource_Singular_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kategorię.
        /// </summary>
        internal static string Resource_Singular_Category {
            get {
                return ResourceManager.GetString("Resource_Singular_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to konfigurację.
        /// </summary>
        internal static string Resource_Singular_Configuration {
            get {
                return ResourceManager.GetString("Resource_Singular_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transakcję.
        /// </summary>
        internal static string Resource_Singular_Transaction {
            get {
                return ResourceManager.GetString("Resource_Singular_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        internal static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły transakcji.
        /// </summary>
        internal static string TransactionDetailView_Title {
            get {
                return ResourceManager.GetString("TransactionDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transakcje.
        /// </summary>
        internal static string TransactionsView_Title {
            get {
                return ResourceManager.GetString("TransactionsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostosuj.
        /// </summary>
        internal static string Widget_ContentView_Button_GoToDetails {
            get {
                return ResourceManager.GetString("Widget_ContentView_Button_GoToDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szybki bilans.
        /// </summary>
        internal static string Widget_FastBalanceContentView_Title {
            get {
                return ResourceManager.GetString("Widget_FastBalanceContentView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły szybkiego bilansu.
        /// </summary>
        internal static string Widget_FastBalanceDetailView_Title {
            get {
                return ResourceManager.GetString("Widget_FastBalanceDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szybki raport.
        /// </summary>
        internal static string Widget_FastReportContentView_Title {
            get {
                return ResourceManager.GetString("Widget_FastReportContentView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły szybkiego raportu.
        /// </summary>
        internal static string Widget_FastReportDetailView_Title {
            get {
                return ResourceManager.GetString("Widget_FastReportDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnie transakcje.
        /// </summary>
        internal static string Widget_LastTransactionsContentView_Title {
            get {
                return ResourceManager.GetString("Widget_LastTransactionsContentView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły ostatnich transakcji.
        /// </summary>
        internal static string Widget_LastTransactionsDetailView_Title {
            get {
                return ResourceManager.GetString("Widget_LastTransactionsDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skróty.
        /// </summary>
        internal static string Widget_ShortcutsContentView_Title {
            get {
                return ResourceManager.GetString("Widget_ShortcutsContentView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostosuj skróty.
        /// </summary>
        internal static string Widget_ShortcutsDetailView_Title {
            get {
                return ResourceManager.GetString("Widget_ShortcutsDetailView_Title", resourceCulture);
            }
        }
    }
}
